# Site settings
baseURL = "https://intentionally-bilingual.github.io/hugosite/"
baseURLReal = "https://intentionally-bilingual.github.io/hugosite/"
languageCode = "en-us"

[languages.en]
  title = "Nimke.nl"
  weight = 1
  LanguageName = "ðŸ‡¬ðŸ‡§ English"
    
[languages.nl]
  title = "Nimke.nl"
  weight = 2
  LanguageName = "ðŸ‡³ðŸ‡± Nederlands"


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

# Site parameters
[params]

    # Meta
    description = "Intentionally Bilingual"
    author = "Nimke Nijhof"
    keywords = "bilingualism, parenting"
    
    # Back-to-top button name
    bttButton = ""
